version: '2.1'

services:
  communigatepro-data:
    network_mode: host
    image: busybox
    container_name: "${DOMAIN_NAME}_communigatepro-data"
    volumes:
      - "${DATA_PATH}:/var/CommuniGate"

  communigatepro:
    environment:
       - "TZ=${TIMEZONE}"
    build:
      context: ./CommunigatePro/
      dockerfile: Dockerfile
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    hostname: ${DOMAIN_NAME}
    volumes_from:
      - communigatepro-data
    container_name: "${DOMAIN_NAME}_cgp"
    depends_on:
      - communigatepro-data
    restart: always
#    logging:
#      driver: none


    network_mode: "host"
